### ISSUE TITLE
Combine efforts with vim-leader-guide

### ISSUE THREAD

**Issue by ctjhoa** [ktonga/vim-follow-my-lead#22]
[hecal3/vim-leader-guide](https://github.com/hecal3/vim-leader-guide) is really cool plugin that has almost the same goal as yours maybe combine efforts ?

/cc @hecal3

**Comment by ktonga** [comment]
I don't think both plugins share the same goal, for some reason @hecal3 decided to start his own plugin instead of contributing to mine after [being inspired](https://www.reddit.com/r/vim/comments/3k13kt/a_vim_key_guide/) by my post.

I think his plugin is much more ambitious, and has a different target audience. The intention of my plugin is really simple, and I prefer it to remain like this, which is just to show a quick help of the leader mappings tacking advantage of the comments you use to put next to them in your `vimrc`.

Thank you anyway.
