### ISSUE TITLE
Description not detected if leader hardcoded

### ISSUE THREAD

**Issue by SnoringFrog** [ktonga/vim-follow-my-lead#9]
I had this old mapping in my vimrc (my leader is comma): 

```
" Clear current search highlighting
nnoremap <silent> ,/ :nohlsearch<CR>
```

While this was detected by `fml`, it's description was not. So the description text ended up being `:nohlsearch<CR>` instead of the comment above it.

**Comment by ktonga** [comment]
This is intentionally not supported, you are mapping to the ',' not to the `<Leader>`. When I parse the output of `:verbose map` the leader is already replaced so I have no way to differentiate from hardcoded. That's why it's included in the mappings. 

It is this way to help you to do the right thing ☺. You should update this **old** mapping so it uses the placeholder.

**Comment by ktonga** [comment]
As commend before it is intentionally not supported.
